services:
  postgres:
    image: postgres:latest
    
    restart: always
    environment:
      POSTGRES_USER: documentuser
      POSTGRES_PASSWORD: documentpass
      POSTGRES_DB: documentdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - redisdata:/data   
volumes:
  pgdata:
  redisdata:
